In [ ]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
import numpy as np

In [ ]:
iris = load_iris()
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [ ]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), iris.data, iris.target,cv=3)

array([0.96, 0.96, 0.94])

In [ ]:
cross_val_score(SVC(gamma='auto'),iris.data,iris.target,cv=3)

array([0.98, 0.98, 0.96])

In [ ]:
cross_val_score(RandomForestClassifier(n_estimators=30),iris.data,iris.target,cv=3)

array([0.98, 0.94, 0.98])

In [ ]:
cross_val_score(DecisionTreeClassifier(),iris.data,iris.target,cv=3)

array([0.98, 0.92, 1.  ])

**Take average**

In [ ]:
np.average(cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), iris.data, iris.target,cv=3))

0.9533333333333333

In [ ]:
np.average(cross_val_score(SVC(gamma='auto'),iris.data,iris.target,cv=3))

0.9733333333333333

In [ ]:
np.average(cross_val_score(RandomForestClassifier(n_estimators=30),iris.data,iris.target,cv=3))

0.96

In [ ]:
np.average(cross_val_score(DecisionTreeClassifier(),iris.data,iris.target,cv=3))

0.9666666666666667