<img src='Capture.png'>

In [1]:
import numpy as np

1) Convert to inr

In [5]:
revenue_usd = np.array([[200, 68, 110, 80], [220, 79, 140, 85], [250, 105, 180, 90]])
revene_usd

array([[200,  68, 110,  80],
       [220,  79, 140,  85],
       [250, 105, 180,  90]])

In [6]:
revenue = revene_usd * 75
revenue

array([[15000,  5100,  8250,  6000],
       [16500,  5925, 10500,  6375],
       [18750,  7875, 13500,  6750]])

2) Flowers

In [7]:
units = np.array([[50, 10, 40], [60, 13, 70], [25, 5, 52]])
units

array([[50, 10, 40],
       [60, 13, 70],
       [25,  5, 52]])

In [8]:
price_per_unit = np.array([20, 30, 15])

In [9]:
units * price_per_unit

array([[1000,  300,  600],
       [1200,  390, 1050],
       [ 500,  150,  780]])

In [11]:
total_sales = np.dot(units, price_per_unit)
total_sales

array([1900, 2640, 1430])